name: SpawnCooldownPlugin
version: 1.0
main: com.anya.spawncooldown.SpawnCooldownPlugin
api-version: 1.20
commands:
  spawn:
    description: Custom spawn command with cooldown and damage check
    usage: /spawn